# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project1_1_H' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project1_1_H
  pod 'SnapKit', '~> 5.6.0'
  target 'Project1_1_HTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project1_1_HUITests' do
    # Pods for testing
  end

end
